sudo: false
language: node_js

matrix:
  include:
  - node_js: stable
    env: CXX=g++-4.8

script:
  - npm run lint

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
